//
//  NTStyleKit.h
//  ProjectName
//
//  Created by Michel on 2/17/15.
//  Copyright (c) 2015 BigZero. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface NTStyleKit : NSObject

// Drawing Methods
+ (void)drawIconWithFrame: (CGRect)frame isPressed: (BOOL)isPressed;
+ (void)drawMicWhite;
+ (void)drawMic;

// Generated Images
+ (UIImage*)imageOfIconWithFrame: (CGRect)frame isPressed: (BOOL)isPressed;

@end
